version: '3.2'
services:
  db:
    container_name: hackteeth_db
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: dentist
      MYSQL_ROOT_HOST: '%'
    build: 
      context: ./mysql_server
      dockerfile: Dockerfile
  flask:
    container_name: hackteeth_api
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    command: python simpleFlask.py
    restart: always
  app:
    container_name: hackteeth_app
    environment:
      DB_ADDRESS: hackteeth_db
      DB_PORT: 3306
    build:
      context: ./java_server
      dockerfile: Dockerfile
    depends_on:
      - db
    command: "bash ./wait_for_db.sh"
  nginx:
   container_name: some-nginx
   build:
    context: ./nginx/
   restart: always
   ports:
      - 80:80
   depends_on:
      - flask
      - app
