version: '3.2'

services:

  db:
    container_name: hackteeth_db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: dentist
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    build: 
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./mysql_dump:/docker-entrypoint-initdb.d
  app:
    image: whitenguyen2512/hack_my_teeth:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    
